type Query {
  menproducts: [Menproducts]
  menproduct(id: Int!): Menproducts
}

type Menproducts {
  id: Int
  title: String
  summary: String
  description: String
  image: String
  category_id: Int
  created_at: String
}
