
type Query {
  womenproduct: [WomenProducts]
  womendetail(id: Int!): WomenProducts
}

type WomenProducts {
  id: Int
  title: String
  summary: String
  description: String
  image: String
  category_id: Int
  created_at: String
}
